site_name: Fundamentos de Machine Learning
theme:
  name: material
  palette:
    # Paleta para el modo claro (día)
    - scheme: default
      primary: green # Un color base, pero será anulado por tu CSS
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro

    # Paleta para el modo oscuro (noche)
    - scheme: slate
      primary: green # También será anulado si defines colores para slate en tu CSS
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

# --- Sección de Personalización ---
custom_dir: overrides
extra_css:
  - extra.css

# AGREGAR ESTA SECCIÓN:
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - 'Introducción: Aprendizaje automatico ': 'index.md'
  - 'semana1: Modelos': 'semana1.md'
  - 'semana2: Datos': 'semana2.md'
  - 'semana3: Modelos Avanzados': 'semana3.md'
  - 'semana4: ML en el mundo real': 'semana4.md'


